### ISSUE TITLE
Failing due to an SSL error.

### ISSUE THREAD

**Issue by kareemserry** [AhmedAshrafAZ/cms-downloader#5]
```
TypeError: Cannot read property 'statusCode' of undefined
    at D:\guc9th\cms-downloader\index.js:33:15
    at D:\guc9th\cms-downloader\node_modules\httpntlm\httpntlm.js:99:18
    at finalCallback (D:\guc9th\cms-downloader\node_modules\httpreq\lib\httpreq.js:98:7)
    at ClientRequest.<anonymous> (D:\guc9th\cms-downloader\node_modules\httpreq\lib\httpreq.js:428:5)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

![image](https://user-images.githubusercontent.com/43077693/97807514-f4d9f280-1c69-11eb-9862-9058039973e3.png)

this request is failing, and returning and error instead of a response. Logging the error returns this.
```
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1496:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:938:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:696:12) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}
```

https://github.com/nodejs/node/issues/33705

this seems to be a server side issue, but maybe there is a way to work around it.

**Comment by AhmedAshrafAZ** [comment]
Hello Kareem,
This issue was solved earlier today. Can you please try "git pull origin main" then "npm start"? Then tell me again if there is still an issue.

**Comment by kareemserry** [comment]
can confirm this is working in the new version.
